package org.metahut.starfish.parser.domain.enums;

/**
 *
 */
public enum SfRelType {
    /**
     * custom classes which are generated by janino
     */
    CUSTOM,
    /**
     * classes which are in jdk or in jars
     */
    DEFAULT;
}
