spring:
  main:
    web-application-type: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=CST
    username: test
    password: test
  sql:
    init:
      schema-locations: "classpath:sql/starfish_h2.sql"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


starfish:
  scheduler:
    type: dolphinscheduler
    dolphinscheduler:
      service-url: http://dolphinscheduler.dev.zhaopin.com/dolphinscheduler
      project-code: 4996418468000
  ingestion:
    service-address: localhost:8802
    collector-execute-rest: http://{0}/collector/execute
